### ISSUE TITLE
KenLM model

### ISSUE THREAD

**Issue by SultanovAR** [lrank/Linguistic_adversity#1]
Hi, where I can find the kenLM pertained model, that you used in "WN" noise generator.

**Comment by lrank** [comment]
Hi, SultanovAR.

Technically, you can train the language model yourself by checking this:
https://kheafield.com/code/kenlm/
or an easier way that is following the instructions in moses:
http://www.statmt.org/moses/
to see how to build a language model file using a corpus.

Or I can share mine tomorrow for you as I am off work now.
Thank you for your patient.

**Comment by SultanovAR** [comment]
Thanks for the help, I have already trained lm with the instruction in moses
